### ISSUE TITLE
Question: how to use these scripts

### ISSUE THREAD

**Issue by mzico** [ludomp/opendj-utils#1]
Hi @ludomp , 
Thanks for these script, first of all. I am little curious how to run these scripts? I am trying to use 'filterstat.py'. Here is what I tried: 
- Tried to run that from /home/ldap/ with `python filterstat.py -o output.ldif` but seems like 'output.ldif' is blank. 

Any hint?

**Comment by ludomp** [comment]
All scripts have a usage that is triggered by --help
Most of the scripts need input files. Unless there is an input, there is no output.

**Comment by mzico** [comment]
Thanks for quick response! 
Seems like some exception is there... may be I am missing something! 

```
[ldap@zico OPENDJ_JAN19_17_ETIME_WORK]$ python filterstat.py access -o output.ldif
processing file: access
Traceback (most recent call last):
  File "filterstat.py", line 142, in <module>
    sys.exit(main())
  File "filterstat.py", line 103, in main
    except err:
UnboundLocalError: local variable 'err' referenced before assignment
```

**Comment by ludomp** [comment]
Sorry, I haven't run them for some time. These are open source, not supported scripts...

**Comment by ludomp** [comment]
But I've just tests with files from customers and the script works fine...
Note that the usage says : 
Usage: filterstat.py [options] file [file ...]
So, the -o output.ldif should not be at the end of the command.

**Comment by mzico** [comment]
>> So, the -o output.ldif should not be at the end of the command.

Exactly! Thanks much for your help!! 

Here is how it's working: `python filterstat.py -o output.ldif access`
